const APPNAME = "Student Tour Portal";


const BGCOLOR = "#EEEEEE";
const PRIMARYCOLOR = "#FAF9EE";
const SECONDARYCOLOR = "#DCCFC0";
const TEXTCOLOR = "#050505";
const DISABLEDTEXTCOLOR = "#65676b";



export { APPNAME ,BGCOLOR, PRIMARYCOLOR, SECONDARYCOLOR, TEXTCOLOR, DISABLEDTEXTCOLOR };